version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WordOfTheDayBE"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16m9f3mjh7ma5"
s3_prefix = "WordOfTheDayBE"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
