AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  word-of-the-day-be


Parameters:
  DomainName:
    Type: String
  Certificate:
    Type: String
  HostedZoneId:
    Type: String
  Subdomain:
    Type: String
  Secret:
    Type: String


Resources:

#  GetDashboardDataAPIEndpoint:
#    Type: AWS::Serverless::Api
#    DependsOn: GetDashboardDataFunction
#    Properties:
#      Cors:
#        AllowMethods: "'*'"
#        AllowHeaders: "'*'"
#        AllowOrigin: "'https://wordsoftheday.org'"
#        AllowCredentials: True
#      StageName: prod
#      Domain:
#        DomainName: !Join [ '', [ !Ref Subdomain, ., !Ref DomainName ] ]
#        CertificateArn: !Ref Certificate
#        Route53:
#          HostedZoneId: !Ref HostedZoneId

#  GetDashboardDataFunction:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: get_dashboard_data/
#      Handler: app.lambda_handler
#      Runtime: python3.8
#    Environment:
#      Variables:
#        SECRET: !Ref Secret
#    Events:
#      GetDashboardDataEvent:
#        Type: Api
#        Properties:
#          RestApiId: !Ref IndexOperationsAPIEndpoint
#          Path: /{}
#          Method: any


  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: index_operations/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          SECRET: !Ref Secret
      Events:
        IndexOperationsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref APIEndpoint
            Path: /{path+}
            Method: any

  APIEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'https://wordsoftheday.org'"
        AllowCredentials: True
      StageName: prod
      Domain:
        DomainName: !Join ['', [!Ref Subdomain, ., !Ref DomainName]]
        CertificateArn: !Ref Certificate
        Route53:
          HostedZoneId: !Ref HostedZoneId

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_email
          AttributeType: S
      KeySchema:
        - AttributeName: user_email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: WordsOfTheDayUsersTable
