AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  word-of-the-day-be

Parameters:
  DomainName:
    Type: String
  Certificate:
    Type: String
  HostedZoneId:
    Type: String
  Subdomain:
    Type: String


Resources:
  IndexOperationsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: index_operations/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        IndexOperations:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIEndpoint
            Path: /index-operation
            Method: get
  APIEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: stage
      Domain:
        DomainName: !Join ['', [!Ref Subdomain, ., !Ref DomainName]]
        CertificateArn: !Ref Certificate
        Route53:
          HostedZoneId: !Ref HostedZoneId